package com.rakayby.blog.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import java.util.Date;
import lombok.Getter;
import lombok.Setter;

/**
 *
 * @author Rakayby
 */
@Getter
@Setter
@DynamoDBTable(tableName = "Posts")
public class Post {

    @DynamoDBHashKey()
    @DynamoDBAutoGeneratedKey
    private Long id;
    @DynamoDBAttribute
    private String slug;
    @DynamoDBAttribute
    private String title;
    @DynamoDBAttribute
    private String content;
    @DynamoDBAttribute
    private String tag;
    @DynamoDBAttribute
    private Date date;
    @DynamoDBAttribute
    private Integer readTime;
    @DynamoDBAttribute
    private String summary;
}
